:defaults: &defaults
  :host: localhost
  :slaves:
    # - host: localhost
      # port: 27018
    # - host: localhost
      # port: 27019
  :allow_dynamic_fields: false
  :parameterize_keys: false
  :persist_in_safe_mode: false
  :raise_not_found_error: false
  :reconnect_time: 5
  :use_object_ids: true
  :persist_types: false
  :option_no_exist: false

:test:
  <<: *defaults
  :name: checklist_hub_test

:development:
  <<: *defaults
  :name: checklist_hub_development
